### ISSUE TITLE
Suggest one site with multiple language support

### ISSUE THREAD

**Issue by buckaroogeek** [usagov/usa.gov#4]
Rather than a completely separate site for Spanish language content I recommend that the back end CMS (and APIs) deliver content in the language according the preference set in the browser or get request. This would more easily scale to other languages (if needed).

**Comment by smileytech** [comment]
Thanks for the feedback!  We don’t use the user’s browser preference to determine if they should see English or Spanish content because we don’t want to assume users who might elect to use an English browser only wants to access USA.gov (and likewise for GobiernoUSA.gov).    For example, users might be bilingual and want to use both sites.  Additionally, GobiernoUSA.gov is not a direct translation of USA.gov.  While the topics covered are similar, the exact content offered on the two sites is different based on the content available on other government websites and what the audience of each site is looking for.
